version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:light

jobs:
  terraform_plan:
    executor: terraform
    steps:
      - run:
          name: Terraform Plan
          command: terraform init && terraform plan --var-file terraform.tfvars
      - persist_to_workspace:
          root: /root
          paths:
            - project

  terraform_apply:
    executor: terraform
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Terraform Apply
          command: terraform apply --var-file terraform.tfvars

workflows:
  version: 2
  deploy:
    jobs:
      - terraform_plan
      - terraform_apply:
          requires:
            - terraform_plan
