version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:light

  zip:
    docker:
      - image: mauodias/alpine-zip:latest

jobs:
  package_files:
    executor: zip
    steps:
      - checkout
      - run:
          name: Zip function files
          command: zip mazegen.zip * -D
      - persist_to_workspace:
          root: /root
          paths:
            - project

  terraform_plan:
    executor: terraform
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Terraform Plan
          command: pwd && terraform init && terraform plan

  terraform_apply:
    executor: terraform
    steps:
      - run:
          name: Terraform Apply
          command: terraform apply
      - attach_workspace:
          at: /root

workflows:
  version: 2
  deploy:
    jobs:
      - package_files
      - terraform_plan:
          context: gcp
          requires:
            - package_files
      - terraform_apply:
          context: gcp
          requires:
            - terraform_plan
